name: Semantic Release
description: Runs Semantic Release

runs:
  using: composite
  steps:
  - name: Setup dependencies
    run: npm clean-install
    shell: bash
  - name: Release
    run: npx semantic-release
    env:
      GITHUB_TOKEN: ${{ github.token }}
    shell: bash
