name: Tag
description: Tag using Sementic Versioning

runs:
  using: composite
  steps:
  - uses: actions/checkout@v4
    with:
      fetch-depth: 0
  - name: Testing
    run: ls $GITHUB_ACTION_PATH
    shell: bash
  - name: Setup dependencies
    run: npm clean-install
    shell: bash
  - name: Release
    run: npx semantic-release
    env:
      GITHUB_TOKEN: ${{ github.token }}
    shell: bash
