extends:
- '@commitlint/config-conventional'

rules:
  body-max-line-length:
  - 1
  - always
  - 120
  footer-max-line-length:
  - 1
  - always
  - 120
  type-enum:
  - 2
  - always
  - - chore
    - feat
    - fix
  header-max-length:
  - 1
  - always
  - 120
