name: Build and Publish

on:
  workflow_call:

jobs:
  docker:
    name: Build and Publish Docker
    uses: deepetherlabs/actions/.github/workflows/publish-docker.yml@main
    secrets: inherit
  publish:
    name: Build and Publish Helm Chart
    runs-on: ubuntu-latest
    steps:
    - name: Helm Package and Publish
      uses: appany/helm-oci-chart-releaser@v0.4.1
      with:
        name: ${{ github.event.repository.name }}
        repository: deepetherlabs/helm
        tag: ${{ steps.get_version.outputs.version }}
        path: .
        registry: ghcr.io
        registry_username: ${{ github.actor }}
        registry_password: ${{ github.token }}
        update_dependencies: 'true'
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ github.token }}
    needs: [docker]
