name: Build and Publish

on:
  workflow_call:

jobs:
  publish:
    name: Build and Publish Docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64
    - name: Install DevSpace
      uses: loft-sh/setup-devspace@main
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Get Version Number
      id: get_version
      uses: ${GITHUB_REPOSITORY_OWNER}/actions/version@main
    - name: Build and Publish v${{ steps.get_version.outputs.version }} using DevSpace
      run: devspace build -t ${{ steps.get_version.outputs.version }}
