name: Sync with .NET Template

on:
  workflow_call:

jobs:
  sync:
    name: Sync Repository with sync-dotnet-template
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.SYNC_GITHUB_TOKEN }}
    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: 3.x
    - name: Execute Actions Template Sync
      uses: AndreasAugustin/actions-template-sync@v1
      with:
        github_token: ${{ github.token }}
        source_repo_path: ${{ github.repository_owner }}/sync-dotnet-template
        is_allow_hooks: true
        source_repo_ssh_private_key: ${{ secrets.SOURCE_REPO_SSH_PRIVATE_KEY }}
        is_not_source_github: true
