name: Sync with .NET Template

on:
  workflow_call:

jobs:
  sync:
    name: Sync Repository with sync-dotnet-template
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # submodules: true
        token: ${{ secrets.SYNC_GITHUB_TOKEN }}
    - name: actions-template-sync
      uses: AndreasAugustin/actions-template-sync@v1
      with:
        github_token: ${{ secrets.SYNC_GITHUB_TOKEN }}
        source_repo_path: deepetherlabs/sync-dotnet-template
        is_allow_hooks: true
