name: Sync with .NET Template

on:
  workflow_call:

jobs:
  sync:
    name: Sync Repository with sync-dotnet-template
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ github.token }}
    - name: Execute Actions Template Sync
      uses: AndreasAugustin/actions-template-sync@v1
      with:
        github_token: ${{ github.token }}
        source_repo_path: ${{ github.repository_owner }}/sync-dotnet-template
        source_repo_ssh_private_key: ${{ secrets.SYNC_DOTNET_TEMPLATE_SSH_PRIVATE_KEY }}
        git_remote_pull_params: "--allow-unrelated-histories --squash --strategy=recursive"
        pr_title: Sync with .NET Template
        is_allow_hooks: true
        is_not_source_github: true
