name: Tag

on:
  workflow_call:

jobs:
  tag_release:
    name: Tag Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Release
      uses: deepetherlabs/actions/semantic-release@main
