name: Tag, Build and Publish

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  tag_release:
    name: Tag Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup dependencies
      run: npm clean-install
    - name: Release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ github.token }}
